import { describe,it,expect } from 'vitest';
import { ClaimsEngine, canonicalize, commitment, payout } from '../src/domain.js';
import { demoPolicy } from '../src/fixtures.js';
const caller=demoPolicy.holder;
const other='0x2222222222222222222222222222222222222222';
const claim=(o={})=>({claimId:'clm_test',policyId:demoPolicy.policyId,claimant:caller,validator:demoPolicy.validator,incidentAt:'2026-08-10T12:00:00.000Z',incidentClass:'MISSED_EXECUTION_WINDOW',documentedLoss:600n,finality:'FINAL',explanation:'Bounded claimant explanation.',evidence:[{kind:'DEMO FIXTURE',mode:'fixture',source:'test',finality:'FINAL',usedInAdjudication:false}],...o});
const fact={verified:true,finality:'FINAL',validator:demoPolicy.validator,source:'official protocol record'};
const verdict=(o={})=>({eligibility:'APPROVED',incidentClass:'MISSED_EXECUTION_WINDOW',slashFinal:true,coveredEvent:true,exclusionTriggered:false,eligibleLoss:600n,confidence:.8,evidenceFindings:['supported'],policyFindings:['covered'],reasoningSummary:'Supported in controlled test.',...o});

describe('SLAIV deterministic reference engine',()=>{
  it('canonicalizes equivalent structures identically',async()=>{expect(canonicalize({b:1,a:'x'})).toBe(canonicalize({a:'x',b:1}));expect(await commitment({b:1,a:'x'})).toBe(await commitment({a:'x',b:1}))});
  it('creates immutable policy and rejects duplicate/wrong holder',()=>{const e=new ClaimsEngine();e.createPolicy(demoPolicy,caller);expect(()=>e.createPolicy(demoPolicy,caller)).toThrow('Duplicate');expect(()=>new ClaimsEngine().createPolicy(demoPolicy,other)).toThrow('Unauthorized')});
  it('prevents wrong claimant and duplicate claims',()=>{const e=new ClaimsEngine();e.createPolicy(demoPolicy,caller);expect(()=>e.submitClaim(claim(),other)).toThrow('Unauthorized');e.submitClaim(claim(),caller);expect(()=>e.submitClaim(claim(),caller)).toThrow('Duplicate')});
  it('never trusts claimant-supplied finality and rejects premature review',()=>{const e=new ClaimsEngine();e.createPolicy(demoPolicy,caller);const c=e.submitClaim(claim({finality:'FINAL'}),caller);expect(c.state).toBe('AWAITING_FINALITY');expect(c.finality).toBe('PENDING');expect(()=>e.review(c.claimId,verdict())).toThrow('not ready')});
  it('accepts independently verified finality then permits judgment',()=>{const e=new ClaimsEngine();e.createPolicy(demoPolicy,caller);e.submitClaim(claim(),caller);e.verifyFinality('clm_test',fact);expect(e.review('clm_test',verdict()).state).toBe('APPROVED')});
  it('reviews, caps payout and allows permissionless finalization',()=>{const e=new ClaimsEngine();e.createPolicy(demoPolicy,caller);e.submitClaim(claim(),caller);e.verifyFinality('clm_test',fact);e.review('clm_test',verdict());const c=e.finalize('clm_test',other);expect(c.instruction).toBe(500n);expect(()=>e.finalize('clm_test',caller)).toThrow('cannot be finalized')});
  it('keeps claimant assertions identity-bound while public evidence may be supplied by others',()=>{const e=new ClaimsEngine();e.createPolicy(demoPolicy,caller);e.submitClaim(claim(),caller);expect(()=>e.appendEvidence('clm_test',{kind:'CLAIMANT ASSERTION',mode:'asserted',source:'x',finality:'UNKNOWN',usedInAdjudication:false},other)).toThrow('Unauthorized');expect(()=>e.appendEvidence('clm_test',{kind:'MONITOR OBSERVATION',mode:'observed',source:'public',finality:'UNKNOWN',usedInAdjudication:false},other)).not.toThrow()});
  it('rejects loss above documented',()=>{const e=new ClaimsEngine();e.createPolicy(demoPolicy,caller);e.submitClaim(claim(),caller);e.verifyFinality('clm_test',fact);expect(()=>e.review('clm_test',verdict({eligibleLoss:601n}))).toThrow('exceeds')});
  it('requires claimant to initiate an appeal',()=>{const e=new ClaimsEngine();e.createPolicy(demoPolicy,caller);e.submitClaim(claim(),caller);e.verifyFinality('clm_test',fact);e.review('clm_test',verdict({eligibility:'DENIED',eligibleLoss:0n}));expect(()=>e.appeal('clm_test','New material evidence changes source reconciliation.',{},other)).toThrow('Unauthorized');expect(e.appeal('clm_test','New material evidence changes source reconciliation.',{},caller).state).toBe('APPEALED')});
  it('uses integer arithmetic',()=>{expect(payout(601n,500n,500).payout).toBe(500n);expect(payout(420n,500n,500).payout).toBe(399n)});
});
