'use client';
import Link from 'next/link';
import { PageHead, Stamp } from '../components';
import { allEvidence } from '../lib/genlayer';
import { docket, fmtDate, useLive } from '../live-data';

function Ledger({records,empty}){return <section className="evidence-ledger">{records.length?records.map(({claim,item})=><article className="evidence-record" key={`${claim.claim_id}:${item.evidence_id}`}><header><code>{item.evidence_id}</code><Stamp state={item.kind==='PROTOCOL_FACT'?'SETTLED':'BOUND'}/></header><dl><div><dt>Claim ID</dt><dd><Link href={`/claims/${claim.claim_id}`}>{docket(claim.claim_id)}</Link></dd></div><div><dt>Validator</dt><dd>{item.validator||claim.validator}</dd></div><div><dt>Event ID</dt><dd>{item.event_id||'—'}</dd></div><div><dt>Network</dt><dd>{item.network||'—'}</dd></div><div><dt>Source</dt><dd>{item.source}</dd></div><div><dt>Reference</dt><dd><a href={item.reference} target="_blank" rel="noreferrer">{item.reference}</a></dd></div><div><dt>SHA-256</dt><dd><code>{item.content_hash}</code></dd></div><div><dt>Submitted at</dt><dd>{fmtDate(item.submitted_at)}</dd></div><div><dt>Submitted by</dt><dd><code>{item.submitter||'contract record unavailable'}</code></dd></div><div><dt>Finality</dt><dd>{item.finality||'ASSERTED'}</dd></div></dl></article>):<p className="empty">{empty}</p>}</section>}

export default function Evidence(){const live=useLive(allEvidence,[]);if(live.loading)return <main className="app-page"><p className="loading">Reading evidence ledger…</p></main>;if(live.error)return <main className="app-page"><div className="read-error">{live.error}</div></main>;const flattened=(live.data||[]).flatMap(({claim,evidence})=>evidence.map(item=>({claim,item}))),protocol=flattened.filter(row=>row.item.kind==='PROTOCOL_FACT'),claimant=flattened.filter(row=>row.item.kind!=='PROTOCOL_FACT');return <main className="app-page"><PageHead eyebrow="EVIDENCE LEDGER" title="Protocol evidence"><p>Stored contract exhibits, separated by trust class. The browser does not create protocol facts.</p></PageHead><h2 className="subhead">Verified protocol facts</h2><Ledger records={protocol} empty="No verified protocol facts recorded."/><h2 className="subhead">Claimant assertions</h2><Ledger records={claimant} empty="No claimant assertions recorded."/></main>}
