import { z } from 'zod';

export const CLAIM_STATES = ['DRAFT','SUBMITTED','EVIDENCE_PENDING','AWAITING_FINALITY','UNDER_REVIEW','APPROVED','PARTIALLY_APPROVED','DENIED','UNRESOLVED','APPEALED','FINAL'];
export const EVENTS = ['MISSED_EXECUTION_WINDOW','MISSED_APPEAL_WINDOW'];
export const ProvenanceSchema = z.object({ kind:z.enum(['PROTOCOL FACT','MONITOR OBSERVATION','CLAIMANT ASSERTION','GENLAYER JUDGMENT','DEMO FIXTURE']), mode:z.enum(['authoritative','observed','asserted','judged','fixture','unavailable']), source:z.string().min(1), url:z.string().url().refine(value=>new URL(value).protocol==='https:',{message:'Only HTTPS evidence URLs are supported'}).optional(), retrievedAt:z.string().datetime().optional(), reference:z.string().optional(), commitment:z.string().regex(/^sha256:[a-f0-9]{64}$/).optional(), finality:z.enum(['FINAL','PENDING','UNKNOWN','UNAVAILABLE']).default('UNKNOWN'), usedInAdjudication:z.boolean().default(false), error:z.string().optional() });
export const PolicySchema=z.object({policyId:z.string().regex(/^pol_[a-zA-Z0-9_-]+$/),holder:z.string().regex(/^0x[a-fA-F0-9]{40}$/),protocol:z.literal('genlayer'),validator:z.string().min(3).max(128),coverageStart:z.string().datetime(),coverageEnd:z.string().datetime(),coverageLimit:z.coerce.bigint().positive(),coveredEvents:z.array(z.enum(EVENTS)).min(1).max(8),exclusions:z.array(z.string().min(1).max(120)).max(8),deductibleBps:z.coerce.number().int().min(0).max(10000),payoutRule:z.literal('min(eligible_loss_after_deductible, coverage_limit)')}).superRefine((p,ctx)=>{if(Date.parse(p.coverageStart)>=Date.parse(p.coverageEnd))ctx.addIssue({code:'custom',message:'coverageStart must precede coverageEnd'})});
export const ClaimSchema=z.object({claimId:z.string().regex(/^clm_[a-zA-Z0-9_-]+$/),policyId:z.string(),claimant:z.string().regex(/^0x[a-fA-F0-9]{40}$/),validator:z.string().min(3),incidentAt:z.string().datetime(),incidentClass:z.enum(EVENTS),documentedLoss:z.coerce.bigint().positive(),finality:z.enum(['FINAL','PENDING','UNKNOWN']),explanation:z.string().max(4000),evidence:z.array(ProvenanceSchema).min(1).max(12)});
export const VerdictSchema=z.object({eligibility:z.enum(['APPROVED','PARTIALLY_APPROVED','DENIED','UNRESOLVED']),incidentClass:z.enum(EVENTS),slashFinal:z.boolean(),coveredEvent:z.boolean(),exclusionTriggered:z.boolean(),eligibleLoss:z.coerce.bigint().nonnegative(),confidence:z.coerce.number().min(0).max(1),evidenceFindings:z.array(z.string().max(300)).max(12),policyFindings:z.array(z.string().max(300)).max(12),reasoningSummary:z.string().max(1200)});
export const canonicalize=value=>{ if(value===null||typeof value==='boolean'||typeof value==='number'||typeof value==='string')return JSON.stringify(value); if(typeof value==='bigint')return JSON.stringify(value.toString()); if(Array.isArray(value))return `[${value.map(canonicalize).join(',')}]`; if(typeof value==='object')return `{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${canonicalize(value[k])}`).join(',')}}`; throw new Error('Unsupported canonical value'); };
export async function commitment(value){const data=new TextEncoder().encode(canonicalize(value));const digest=await crypto.subtle.digest('SHA-256',data);return `sha256:${[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}`}
export function payout(eligibleLoss, limit, deductibleBps){const loss=BigInt(eligibleLoss), cap=BigInt(limit), deductible=loss*BigInt(deductibleBps)/10000n;return {deductible,payout:loss-deductible>cap?cap:loss-deductible};}
const allowed={DRAFT:['SUBMITTED'],SUBMITTED:['AWAITING_FINALITY'],AWAITING_FINALITY:['UNDER_REVIEW'],UNDER_REVIEW:['APPROVED','PARTIALLY_APPROVED','DENIED','UNRESOLVED'],APPROVED:['FINAL'],PARTIALLY_APPROVED:['APPEALED','FINAL'],DENIED:['APPEALED','FINAL'],UNRESOLVED:['APPEALED'],APPEALED:['APPROVED','PARTIALLY_APPROVED','DENIED','UNRESOLVED'],FINAL:[]};

export class ClaimsEngine {
  constructor(){this.policies=new Map;this.claims=new Map;this.appeals=new Map}
  createPolicy(raw,caller){const p=PolicySchema.parse(raw);if(p.holder.toLowerCase()!==caller.toLowerCase())throw Error('Unauthorized policy holder');if(this.policies.has(p.policyId))throw Error('Duplicate policy');this.policies.set(p.policyId,Object.freeze({...p,active:true}));return p}
  submitClaim(raw,caller){const c=ClaimSchema.parse(raw),p=this.policies.get(c.policyId);if(!p)throw Error('Policy not found');if(c.claimant.toLowerCase()!==caller.toLowerCase()||p.holder.toLowerCase()!==caller.toLowerCase())throw Error('Unauthorized claimant');if(c.validator!==p.validator)throw Error('Validator does not match policy');if(this.claims.has(c.claimId))throw Error('Duplicate claim');this.claims.set(c.claimId,{...c,finality:'PENDING',state:'AWAITING_FINALITY',review:null,verifiedProtocolFact:null,finalized:false});return this.claims.get(c.claimId)}
  verifyFinality(id,fact){const c=this.claims.get(id),p=c&&this.policies.get(c.policyId);if(!c||c.state!=='AWAITING_FINALITY'||!fact?.verified||fact.finality!=='FINAL'||fact.validator!==p.validator)throw Error('Protocol finality not verified');c.verifiedProtocolFact=Object.freeze({...fact});c.finality='FINAL';c.state='UNDER_REVIEW';return c}
  transition(id,next){const c=this.claims.get(id);if(!c||!allowed[c.state].includes(next))throw Error(`Invalid transition to ${next}`);c.state=next;return c}
  appendEvidence(id,evidence,caller){const c=this.claims.get(id);if(!c)throw Error('Claim not found');const e=ProvenanceSchema.parse(evidence);if(e.kind==='CLAIMANT ASSERTION'&&c.claimant.toLowerCase()!==caller.toLowerCase())throw Error('Unauthorized evidence mutation');if(c.evidence.some(x=>x.commitment&&x.commitment===e.commitment))throw Error('Duplicate evidence');c.evidence.push(e);return c}
  review(id,rawVerdict){const c=this.claims.get(id);if(!c||c.state!=='UNDER_REVIEW'||!c.verifiedProtocolFact)throw Error('Claim is not ready for review');const v=VerdictSchema.parse(rawVerdict);if(v.eligibleLoss>c.documentedLoss)throw Error('Eligible loss exceeds documented loss');if(!v.slashFinal)throw Error('Non-final slash cannot be adjudicated');c.review=v;c.state=v.eligibility;return c}
  finalize(id){const c=this.claims.get(id);if(!c||c.finalized||!['APPROVED','PARTIALLY_APPROVED','DENIED'].includes(c.state))throw Error('Claim cannot be finalized');c.instruction=c.review.eligibility==='DENIED'?0n:payout(c.review.eligibleLoss,this.policies.get(c.policyId).coverageLimit,this.policies.get(c.policyId).deductibleBps).payout;c.finalized=true;c.state='FINAL';return c}
  appeal(id,ground,newEvidence,caller){const c=this.claims.get(id);if(!c||c.claimant.toLowerCase()!==caller.toLowerCase())throw Error('Unauthorized appeal');if(this.appeals.has(id)||!['DENIED','PARTIALLY_APPROVED','UNRESOLVED'].includes(c.state)||ground.length<20||!newEvidence)throw Error('Invalid appeal');this.appeals.set(id,{ground,newEvidence});c.state='APPEALED';return c}
}
