const fixture=(source,finality='UNKNOWN')=>({kind:'DEMO FIXTURE',mode:'fixture',source,finality,usedInAdjudication:false,error:'No cryptographic evidence commitment exists for this demo fixture.'});
export const demoPolicy={policyId:'pol_demo_atlas',holder:'0x1111111111111111111111111111111111111111',protocol:'genlayer',validator:'validator-demo-atlas',coverageStart:'2026-07-01T00:00:00.000Z',coverageEnd:'2026-10-01T00:00:00.000Z',coverageLimit:500n,coveredEvents:['MISSED_EXECUTION_WINDOW'],exclusions:['holder-caused event','non-final slash'],deductibleBps:500,payoutRule:'min(eligible_loss_after_deductible, coverage_limit)'};
export const scenarios=[
 {id:'clm_approved',name:'Approved',state:'APPROVED',incidentClass:'MISSED_EXECUTION_WINDOW',documentedLoss:420n,eligibleLoss:420n,finality:'FINAL',note:'Covered final event inside the demo policy window.',evidence:[fixture('Simulated protocol evidence','FINAL')]},
 {id:'clm_pending',name:'Awaiting finality',state:'AWAITING_FINALITY',incidentClass:'MISSED_EXECUTION_WINDOW',documentedLoss:180n,eligibleLoss:null,finality:'PENDING',note:'No verdict and no payout: underlying finality is pending.',evidence:[fixture('Simulated non-final event','PENDING')]},
 {id:'clm_denied',name:'Denied',state:'DENIED',incidentClass:'MISSED_EXECUTION_WINDOW',documentedLoss:250n,eligibleLoss:0n,finality:'FINAL',note:'Incident predates the coverage window.',evidence:[fixture('Simulated protocol evidence','FINAL')]},
 {id:'clm_unresolved',name:'Unresolved',state:'UNRESOLVED',incidentClass:'MISSED_EXECUTION_WINDOW',documentedLoss:350n,eligibleLoss:null,finality:'UNKNOWN',note:'Simulated sources conflict; no payout is available.',evidence:[fixture('Conflicting simulated sources','UNKNOWN')]},
 {id:'clm_partial',name:'Partial approval',state:'PARTIALLY_APPROVED',incidentClass:'MISSED_EXECUTION_WINDOW',documentedLoss:800n,eligibleLoss:600n,finality:'FINAL',note:'Only the covered portion is eligible; cap and deductible apply.',evidence:[fixture('Simulated protocol evidence','FINAL')]},
 {id:'clm_appeal',name:'Appeal',state:'APPEALED',incidentClass:'MISSED_EXECUTION_WINDOW',documentedLoss:260n,eligibleLoss:null,finality:'FINAL',note:'Material simulated evidence submitted for re-review.',evidence:[fixture('Simulated appeal evidence','FINAL')]}
];
export const validators=[{id:'validator-demo-atlas',name:'Atlas Operator',status:'DEMO HEALTHY',coverage:'1 policy'},{id:'validator-demo-cobalt',name:'Cobalt Labs',status:'DEMO DEGRADED',coverage:'0 policies'}];
