import './style.css';
import { payout } from './domain.js';
import { scenarios, demoPolicy, validators } from './fixtures.js';
import { GenLayerProtocolAdapter } from './adapter.js';
import { deployment, connectWallet } from './genlayer.js';

const app=document.querySelector('#app'); const adapter=new GenLayerProtocolAdapter({rpcUrl:import.meta.env.VITE_GENLAYER_RPC_URL}); let wallet=null;
const nav=[['Overview','/'],['Validators','/validators'],['Monitor','/monitor'],['Policies','/policies'],['Claims','/claims'],['About','/about']];
const esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const tag=x=>`<button class="tag DEMO-FIXTURE" data-provenance='${encodeURIComponent(JSON.stringify(x))}'>DEMO FIXTURE</button>`;
const link=(label,path,cls='')=>`<a class="${cls}" href="${path}" data-route>${label}</a>`;
function shell(content){const path=location.pathname,d=deployment();return `<aside><div class="logo"><b>SL</b><span>SLAIV</span></div><nav>${nav.map(([n,p])=>link(n,p,`nav ${path===p?'active':''}`)).join('')}<hr/>${link('Network','/monitor','nav')}${link('Settings','/about','nav')}</nav><div class="sidefoot"><span class="live"></span> ${d.configured?'LIVE CONTRACT MODE':'DEMO / FIXTURE MODE'}<br/><small>Not insurance. No guaranteed payout.</small></div></aside><div class="app"><header><div class="network"><span class="live"></span><b>ADAPTER</b><span>${d.configured?'Contract configured':'Unavailable — fail closed'}</span></div><label class="search">⌕ <input id="globalSearch" placeholder="Search known IDs"/></label><span class="block">${d.configured?'STUDIONET':'NO LIVE BLOCK'}</span><button class="wallet" id="wallet" ${d.configured?'':'disabled'}>${wallet?wallet.account:'Connect wallet'}</button></header>${content}</div><div id="drawer" class="drawer"></div>`}
function layout(title,sub,body,action=''){return `<main><div class="title"><div><p class="eyebrow">SLAIV · DEMO FIXTURE MODE</p><h1>${title}</h1><p>${sub}</p></div>${action}</div>${body}</main>`}
function cards(){return `<section class="metrics">${[['MONITORED','2','Demo validators'],['OPEN CLAIMS','6','Demo scenarios'],['AWAITING FINALITY','1','No payout available'],['LIVE EVIDENCE','0','Adapter unavailable']].map(x=>`<article class="metric"><small>${x[0]}</small><strong>${x[1]}</strong><em>${x[2]}</em></article>`).join('')}</section>`}
function overview(){return layout('Overview','Evidence-driven slashing coverage adjudication. All displayed records are fixtures.',cards()+`<section class="grid"><article class="panel"><small>DEMO CLAIM MATRIX</small><h2>State-specific scenarios</h2>${scenarios.map(c=>`<a class="claimline" href="/claims/${c.id}" data-route><b>${esc(c.name)}</b><span class="status ${c.state.replaceAll(' ','-')}"><i></i>${c.state}</span><small>${esc(c.note)}</small></a>`).join('')}</article><article class="panel"><small>TRUTHFUL MONITOR</small><h2>Adapter unavailable</h2><p>No authoritative protocol endpoint has been configured. Slaiv does not infer validator health, slash events, or finality from fixtures.</p>${tag({kind:'DEMO FIXTURE',mode:'fixture',source:'Bundled deterministic demo scenarios',finality:'UNAVAILABLE',usedInAdjudication:false,error:'No configured authoritative source.'})}</article></section>`)}
function validatorsPage(){return layout('Validators','Search demo identities; no validator status is claimed as live.',`<section class="panel tablepanel"><div class="filters"><input id="validatorSearch" placeholder="Search validator"/><button class="filter" id="covered">Covered only</button></div><div class="table"><div class="thead"><span>VALIDATOR</span><span>STATUS</span><span>ACTIVE COVERAGE</span></div>${validators.map(v=>`<a class="trow validator-row" href="/validators/${v.id}" data-route><span><b>${esc(v.id)}</b><small>${esc(v.name)}</small></span><span>${esc(v.status)}</span><span>${esc(v.coverage)}</span></a>`).join('')}</div></section>`)}
function validatorDetail(id){const v=validators.find(x=>x.id===id);if(!v)return notFound();const prov={kind:'DEMO FIXTURE',mode:'fixture',source:'Bundled validator scenario',finality:'UNAVAILABLE',usedInAdjudication:false,error:'Unavailable from configured authoritative source.'};return layout(v.name,'Validator detail does not fabricate unsupported protocol data.',`<section class="claimgrid"><article class="panel"><small>IDENTITY</small><h2>${esc(v.id)}</h2><p>Network: unavailable from configured authoritative source.</p><p>Operator reference: unavailable from configured authoritative source.</p>${tag(prov)}</article><article class="panel"><small>OBSERVATIONS</small><h2>Unavailable</h2><p>No configured authoritative source for status, history, slash events, delegation reference, or finality.</p></article><article class="panel terms"><small>CURRENT WALLET POLICY</small><p>Wallet disconnected. Connect a supported GenLayer wallet to query ownership.</p></article></section>`)}
function policies(){return layout('Policies','Immutable terms are represented by the contract and this demo policy manifest.',`<section class="panel manifest"><small>DEMO FIXTURE · ACTIVE POLICY</small><h2>${esc(demoPolicy.policyId)}</h2><div class="manifestgrid"><span>Subject<b>${esc(demoPolicy.validator)}</b></span><span>Window<b>01 Jul – 01 Oct 2026</b></span><span>Limit<b>${demoPolicy.coverageLimit} test GEN</b></span><span>Deductible<b>${demoPolicy.deductibleBps/100}%</b></span></div><code>${esc(JSON.stringify({...demoPolicy,coverageLimit:demoPolicy.coverageLimit.toString()},null,2))}</code></section>`,link('+ Create policy','/policies/new','primary'))}
function policyNew(){return layout('Create policy','Wallet connection and a deployed SlaivClaims contract are required before writing immutable coverage terms.',`<section class="panel"><form id="policyForm"><label>Validator<input required name="validator" placeholder="Validator identity"/></label><label>Coverage limit (test GEN)<input required type="number" min="1" name="limit"/></label><label>Coverage start<input required type="datetime-local" name="start"/></label><label>Coverage end<input required type="datetime-local" name="end"/></label><p class="formhint">Writes are disabled: wallet disconnected and <code>VITE_SLAIV_CLAIMS_ADDRESS</code> is not configured.</p><button class="primary" disabled>Connect wallet to submit</button></form></section>`)}
function claims(){return layout('Claims','Each fixture follows an independent state timeline. No fixture is a live adjudication.',`<section class="kanban">${['AWAITING_FINALITY','UNDER_REVIEW','APPROVED','PARTIALLY_APPROVED','DENIED','UNRESOLVED','APPEALED'].map(state=>`<div class="kancol"><small>${state}</small>${scenarios.filter(c=>c.state===state).map(c=>`<a class="kcard" href="/claims/${c.id}" data-route><b>${esc(c.name)}</b><p>${esc(c.note)}</p>${tag(c.evidence[0])}</a>`).join('')||'<p class="empty">No scenario</p>'}</div>`).join('')}</section>`,link('+ Submit claim','/claims/new','primary'))}
function claimDetail(id){const c=scenarios.find(x=>x.id===id);if(!c)return notFound();let pay=c.eligibleLoss===null?null:payout(c.eligibleLoss,demoPolicy.coverageLimit,demoPolicy.deductibleBps);return layout(`Claim ${c.name}`,c.note,`<section class="claimgrid"><article class="panel facts"><small>CLAIM FACTS · FIXTURE</small><div class="numbers"><div><span>Documented loss</span><b>${c.documentedLoss} test GEN</b></div><div><span>Eligible loss</span><b>${c.eligibleLoss===null?'Unavailable':`${c.eligibleLoss} test GEN`}</b></div><div><span>Underlying finality</span><b>${c.finality}</b></div></div></article><article class="panel evidence"><small>STATE-SPECIFIC EVIDENCE</small><div class="timeline"><time>DEMO</time><i></i><div>${esc(c.note)}<br/>${tag(c.evidence[0])}</div></div>${c.state==='AWAITING_FINALITY'?'<p>Review and payout are unavailable until an authoritative source confirms underlying finality.</p>':''}</article><aside class="panel terms"><small>LOCKED POLICY TERMS · FIXTURE</small><p>Coverage cap: ${demoPolicy.coverageLimit} test GEN</p><p>Deductible: ${demoPolicy.deductibleBps/100}%</p><hr/>${pay?`<div class="calc"><small>DETERMINISTIC INSTRUCTION</small><span>Eligible loss <b>${c.eligibleLoss} GEN</b></span><span>Deductible <b>−${pay.deductible} GEN</b></span><strong>Payout instruction <b>${pay.payout} GEN</b></strong></div>`:'<p>Payout unavailable. Eligible loss must come from a validated GenLayer verdict.</p>'}</aside></section>`,c.state==='APPEALED'?link('View appeal','/claims/'+c.id+'/appeal','primary'): '')}
function claimNew(){return layout('Submit claim','Claims require a connected holder wallet, active policy, bounded evidence packet, and a deployed contract.',`<section class="panel"><p class="formhint">Unavailable: wallet is disconnected; no contract address is configured. This fails closed rather than storing a client-authoritative claim.</p><button class="primary" disabled>Connect wallet to submit</button></section>`)}
function monitor(){let s=adapter.status();return layout('Monitor','Detection may propose incidents. It cannot approve claims.',`<section class="offline"><div class="offlineicon">×</div><div><small>ADAPTER STATUS</small><h2>${s.mode.toUpperCase()}</h2><p>${esc(s.error)}</p><p>Source: ${esc(s.source)}</p></div></section><section class="panel adapter"><h3>Supported adapter contract</h3><code>getValidatorStatus() · getValidatorHistory() · getSlashEvents()<br/>getFinalityStatus() · getDelegationReference()</code><p>All capabilities are unavailable until an authoritative source implementation is configured and verified.</p></section>`)}
function about(){return layout('About Slaiv','Stake risk, judged in context.',`<section class="panel"><h2>Coverage adjudication, not insurance.</h2><p>Native protocol data establishes events; locked policy terms establish rules; GenLayer adjudicates evidence; deterministic integer arithmetic creates the payout instruction.</p><p>Current mode: demo fixture. Contract deployment: unavailable — no deployed address is configured.</p></section>`)}
function notFound(){return layout('Not found','The requested route does not exist.',`<section class="panel">${link('Return to overview','/','primary')}</section>`)}
function render(){const p=location.pathname;let page=p==='/'?overview():p==='/validators'?validatorsPage():p.startsWith('/validators/')?validatorDetail(decodeURIComponent(p.split('/')[2])):p==='/policies'?policies():p==='/policies/new'?policyNew():p==='/claims'?claims():p==='/claims/new'?claimNew():p.match(/^\/claims\/[^/]+\/appeal$/)?claimDetail(p.split('/')[2]):p.startsWith('/claims/')?claimDetail(p.split('/')[2]):p==='/monitor'?monitor():p==='/about'?about():notFound();app.innerHTML=shell(page);bind()}
function bind(){document.querySelector('#wallet')?.addEventListener('click',async()=>{try{wallet=await connectWallet();render()}catch(error){console.error(error)}});document.querySelector('#covered')?.addEventListener('click',e=>{e.currentTarget.classList.toggle('selected');const on=e.currentTarget.classList.contains('selected');document.querySelectorAll('.validator-row').forEach(x=>x.hidden=on&&x.textContent.includes('0 policies'))});document.querySelectorAll('[data-route]').forEach(a=>a.onclick=e=>{e.preventDefault();history.pushState({},'',a.href);render()});document.querySelector('#globalSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter'){const q=e.target.value.trim();const c=scenarios.find(x=>x.id===q),v=validators.find(x=>x.id===q);if(c){history.pushState({},'',`/claims/${c.id}`);render()}else if(v){history.pushState({},'',`/validators/${v.id}`);render()}}});document.querySelector('#validatorSearch')?.addEventListener('input',e=>document.querySelectorAll('.validator-row').forEach(x=>x.hidden=!x.textContent.toLowerCase().includes(e.target.value.toLowerCase())));document.querySelectorAll('[data-provenance]').forEach(x=>x.onclick=()=>drawer(JSON.parse(decodeURIComponent(x.dataset.provenance))))}
function drawer(p){let d=document.querySelector('#drawer');d.className='drawer open';d.innerHTML=`<button class="close">×</button><small>PROVENANCE INSPECTION</small><h2>${esc(p.kind)}</h2>${[['SOURCE TYPE',p.mode],['SOURCE',p.source],['URL / RPC',p.url||'Not available'],['RETRIEVED AT',p.retrievedAt||'Not retrieved'],['BLOCK / TX',p.reference||'Not available'],['EVIDENCE COMMITMENT',p.commitment||'No commitment exists'],['FINALITY',p.finality],['USED IN ADJUDICATION',String(p.usedInAdjudication)],['RETRIEVAL ERROR',p.error||'None']].map(x=>`<div><small>${x[0]}</small><p>${esc(x[1])}</p></div>`).join('')}`;d.querySelector('.close').onclick=()=>d.className='drawer'} window.onpopstate=render;render();
