import './style.css';

const validators = [
  { id:'0x8A…19F', name:'Atlas Operator', status:'HEALTHY', uptime:'99.98%', coverage:'2 policies', incident:'—', slash:'NONE', finality:'FINAL' },
  { id:'0xC1…7D2', name:'Cobalt Labs', status:'DEGRADED', uptime:'99.41%', coverage:'1 policy', incident:'INC-02841', slash:'OBSERVED', finality:'PENDING' },
  { id:'0x4E…B8A', name:'Northstar Node', status:'HEALTHY', uptime:'99.94%', coverage:'0 policies', incident:'—', slash:'NONE', finality:'FINAL' },
  { id:'0x91…3C4', name:'Kinetic Stake', status:'INCIDENT', uptime:'97.88%', coverage:'1 policy', incident:'INC-02837', slash:'FINAL', finality:'FINAL' },
];
const claims = [
  {id:'SL-1049', state:'UNDER REVIEW', validator:'0x8A…19F', loss:420, limit:500, deductible:500, event:'MISSED EXECUTION WINDOW', time:'09 Aug 2026 · 12:41 UTC'},
  {id:'SL-1050', state:'AWAITING FINALITY', validator:'0xC1…7D2', loss:180, limit:250, deductible:500, event:'MISSED APPEAL WINDOW', time:'12 Aug 2026 · 17:12 UTC'},
  {id:'SL-1047', state:'APPROVED', validator:'0x91…3C4', loss:650, limit:500, deductible:500, event:'MISSED EXECUTION WINDOW', time:'04 Aug 2026 · 08:20 UTC'},
];
const provenance = { 'PROTOCOL FACT': ['Native protocol data','GenLayer testnet adapter','13 Aug 2026, 14:22:18 UTC','Block 18,492,114 · TX 0xa98…f120','sha256: e1b4c9d8…19df','Yes — finality check'], 'GENLAYER JUDGMENT': ['GenLayer verdict','SlaivClaims review_slashing_claim','13 Aug 2026, 14:23:02 UTC','Review #rvw_1049','sha256: b8c2f34d…62a1','Yes — eligibility finding'], 'DEMO FIXTURE': ['Demo fixture','Local demo data','Build-time fixture','Not applicable','sha256: demo-fixture-02841','No — illustrative only'], 'CLAIMANT ASSERTION': ['Claimant assertion','Connected wallet submission','13 Aug 2026, 14:19:08 UTC','Claim #SL-1049','sha256: 293a…a780','Yes — corroborated'] };
let active='Overview', selectedClaim=claims[0], selectedValidator=validators[0], coveredOnly=false;
const tag = (kind='DEMO FIXTURE') => `<button class="tag ${kind.replaceAll(' ','-')}" data-prov="${kind}">${kind}</button>`;
const status = s => `<span class="status ${s.replaceAll(' ','-')}"><i></i>${s}</span>`;
function sidebar(){ return `<aside><div class="logo"><b>SL</b><span>SLAIV</span></div><nav>${['Overview','Validators','Monitor','Policies','Claims','Incidents','Activity'].map(x=>`<button class="nav ${active===x?'active':''}" data-page="${x}">${x}</button>`).join('')}<hr/>${['Network','Settings','Wallet'].map(x=>`<button class="nav" data-page="${x}">${x}</button>`).join('')}</nav><div class="sidefoot"><span class="live"></span> TESTNET / DEMO<br/><small>Not insurance. No guaranteed payout.</small></div></aside>` }
function topbar(){return `<header><div class="network"><span class="live"></span><b>NETWORK HEALTH</b><span>GenLayer testnet · stable</span></div><label class="search">⌕ <input id="globalSearch" placeholder="Search validator, claim, hash"/></label><span class="block">BLOCK 18,492,114</span><button class="wallet">0x71…A92 ▾</button></header>`}
function metrics(){return `<section class="metrics">${[['MONITORED','128','Validators tracked'],['OPEN CLAIMS','4','Across active policies'],['AWAITING FINALITY','2','Native status pending'],['INCIDENTS','3','Last 30 days']].map(([l,v,s])=>`<article class="metric"><small>${l}</small><strong>${v}</strong><em>${s}</em>${tag('DEMO FIXTURE')}</article>`).join('')}</section>`}
function overview(){return `<main><div class="title"><div><p class="eyebrow">OPERATIONS CONSOLE</p><h1>Overview</h1><p>Evidence-driven slashing coverage adjudication.</p></div><button class="primary" data-page="Policies">+ Create policy</button></div>${metrics()}<section class="grid"><article class="panel health"><div class="panelhead"><div><small>VALIDATOR HEALTH</small><h2>Observed network status</h2></div><button data-page="Validators">View all →</button></div>${validators.slice(0,3).map(v=>`<div class="healthrow"><b>${v.id}</b><span>${v.name}</span>${status(v.status)}<strong>${v.uptime}</strong></div>`).join('')}<footer>${tag('DEMO FIXTURE')} Fixture data is clearly marked; connect an adapter for live observations.</footer></article><article class="panel"><div class="panelhead"><div><small>CLAIM PIPELINE</small><h2>Requires attention</h2></div><button data-page="Claims">Open queue →</button></div>${claims.slice(0,2).map(c=>`<button class="claimline" data-claim="${c.id}"><span>${status(c.state)}</span><b>#${c.id}</b><small>${c.event}</small><strong>${c.loss} GEN</strong></button>`).join('')}<div class="pipeline"><span>SUBMITTED</span><span>EVIDENCE</span><span>FINALITY</span><span class="on">REVIEW</span><span>FINAL</span></div></article><article class="panel slash"><div class="panelhead"><div><small>RECENT SLASH EVENTS</small><h2>Evidence status</h2></div></div><div class="event"><div class="sev high">!</div><div><b>INC-02841 · Missed execution window</b><p>Slash event seen; awaiting native finality confirmation.</p>${tag('PROTOCOL FACT')}</div><time>12:47 UTC</time></div><div class="event"><div class="sev med">▲</div><div><b>INC-02837 · Missed appeal window</b><p>Final slash event bound to policy pol_001.</p>${tag('DEMO FIXTURE')}</div><time>04 Aug</time></div></article><article class="panel exposure"><small>COVERAGE EXPOSURE</small><h2>1,250 <span>test GEN</span></h2><p>Across 4 active demo policies</p><div class="bar"><i style="width:64%"></i></div><footer>${tag('DEMO FIXTURE')} No TVL or yield is implied.</footer></article></section></main>`}
function validatorsPage(){let rows=validators.filter(v=>!coveredOnly||v.coverage!=='0 policies');return `<main><div class="title"><div><p class="eyebrow">VALIDATOR REGISTRY</p><h1>Validators</h1><p>Protocol status, public evidence, and coverage associations.</p></div></div><section class="panel tablepanel"><div class="filters"><input id="validatorSearch" placeholder="Search validator or operator"/><button class="filter ${coveredOnly?'selected':''}" id="covered">Covered only</button><button class="filter">All networks ▾</button><button class="filter">Status ▾</button></div><div class="table"><div class="thead"><span>VALIDATOR</span><span>STATUS</span><span>UPTIME / OBSERVED HEALTH</span><span>ACTIVE COVERAGE</span><span>LAST INCIDENT</span><span>SLASH STATUS</span><span>FINALITY</span></div>${rows.map(v=>`<button class="trow" data-validator="${v.id}"><span><b>${v.id}</b><small>${v.name}</small></span><span>${status(v.status)}</span><span><b>${v.uptime}</b><small>Adapter fixture</small></span><span>${v.coverage}</span><span>${v.incident}</span><span>${v.slash}</span><span>${status(v.finality)}</span></button>`).join('')}</div></section></main>`}
function claimDetail(c=selectedClaim){let deduction=(c.loss*c.deductible/10000), payout=Math.min(c.loss-deduction,c.limit);return `<main><button class="back" data-page="Claims">← Claims</button><div class="title claimtitle"><div><p class="eyebrow">CLAIM #${c.id}</p><h1>${c.state}</h1><p>${c.event} · ${c.validator}</p></div>${status(c.state)}</div><section class="claimgrid"><article class="panel facts"><small>CLAIM FACTS</small><div class="numbers"><div><span>Claimed loss</span><b>${c.loss} GEN</b></div><div><span>Coverage limit</span><b>${c.limit} GEN</b></div><div><span>Policy period</span><b>01 Jul – 01 Oct</b></div></div>${tag('CLAIMANT ASSERTION')} Claim submitted by policy holder.</article><article class="panel evidence"><small>EVIDENCE / TIMELINE</small>${[['12:41','Monitor detected event','DEMO FIXTURE'],['12:42','Protocol evidence captured','PROTOCOL FACT'],['12:47','Slash event observed','PROTOCOL FACT'],['13:03','Finality verified','PROTOCOL FACT'],['14:22','Claim eligible for review','GENLAYER JUDGMENT']].map(x=>`<div class="timeline"><time>${x[0]}</time><i></i><div>${x[1]}<br/>${tag(x[2])}</div></div>`).join('')}</article><aside class="panel terms"><small>LOCKED POLICY TERMS</small><h3>pol_001</h3><p>Covered events</p><code>["MISSED_EXECUTION_WINDOW",<br/> "MISSED_APPEAL_WINDOW"]</code><p>Exclusions</p><code>holder-caused event<br/>non-final slash</code><hr/><div class="calc"><small>DETERMINISTIC PAYOUT</small><span>Eligible loss <b>${c.loss} GEN</b></span><span>Deductible (${c.deductible/100}%) <b>−${deduction} GEN</b></span><span>Coverage cap <b>${c.limit} GEN</b></span><strong>Payout instruction <b>${payout} GEN</b></strong></div>${tag('DEMO FIXTURE')}</aside></section><section class="panel review"><div><small>GENLAYER REVIEW PIPELINE</small><h2>Coverage adjudication</h2></div><ol>${['Policy loaded','Validator matched','Incident verified','Finality verified','Coverage adjudication','Verdict'].map((x,i)=>`<li class="${i<4?'done':i===4?'current':''}">${i<4?'✓':i===4?'●':'○'} ${x}</li>`).join('')}</ol><p>The review provides eligibility only. The payout above is calculated deterministically under locked terms.</p>${tag('GENLAYER JUDGMENT')}</section></main>`}
function claimsPage(){return `<main><div class="title"><div><p class="eyebrow">ADJUDICATION QUEUE</p><h1>Claims</h1><p>Claims move forward only when native evidence and policy terms align.</p></div><button class="primary" id="newClaim">+ Submit claim</button></div><section class="kanban">${['SUBMITTED','EVIDENCE','AWAITING FINALITY','UNDER REVIEW','FINAL'].map(col=>`<div class="kancol"><small>${col}</small>${claims.filter(c=>c.state===col||(col==='FINAL'&&c.state==='APPROVED')).map(c=>`<button class="kcard" data-claim="${c.id}"><b>#${c.id}</b>${status(c.state)}<p>${c.event}</p><small>${c.loss} GEN · ${c.validator}</small>${tag('DEMO FIXTURE')}</button>`).join('')||'<p class="empty">No claims</p>'}</div>`).join('')}</section></main>`}
function monitor(){return `<main><div class="title"><div><p class="eyebrow">PROTOCOL ADAPTER</p><h1>Monitor</h1><p>Detection proposes incidents. It does not approve claims.</p></div></div><section class="offline"><div class="offlineicon">×</div><div><small>ADAPTER STATUS</small><h2>MONITOR OFFLINE</h2><p>No live protocol observations are being received. Last successful update: 13:42:18 UTC.</p>${tag('DEMO FIXTURE')}</div><button class="primary" id="retry">Retry connection</button></section><section class="panel adapter"><h3>ProtocolAdapter interface</h3><code>getValidatorStatus() · getValidatorHistory() · getSlashEvents()<br/>getFinalityStatus() · getDelegationReference()</code><p>Structured authoritative endpoints must be configured before live use. Fetched evidence is treated as untrusted data, never instruction text.</p></section></main>`}
function policies(){return `<main><div class="title"><div><p class="eyebrow">COVERAGE CONFIGURATION</p><h1>Policies</h1><p>Terms lock when coverage begins. Demo policies use test GEN only.</p></div><button class="primary" id="createPolicy">+ Create policy</button></div><section class="panel manifest"><div><small>ACTIVE · pol_001</small><h2>Atlas Operator Coverage</h2><div class="manifestgrid"><span>Subject<b>Validator 0x8A…19F</b></span><span>Window<b>01 Jul – 01 Oct 2026</b></span><span>Limit<b>500 test GEN</b></span><span>Deductible<b>5.00%</b></span></div><h3>Configuration manifest</h3><code>{<br/> &nbsp;"covered_events": ["MISSED_EXECUTION_WINDOW", "MISSED_APPEAL_WINDOW"],<br/> &nbsp;"exclusions": ["holder-caused event", "non-final slash"],<br/> &nbsp;"payout_rule": "min(eligible_loss_after_deductible, coverage_limit)"<br/>}</code>${tag('DEMO FIXTURE')}</section></main>`}
function render(){let content=active==='Overview'?overview():active==='Validators'?validatorsPage():active==='Claims'?claimsPage():active==='Monitor'?monitor():active==='Policies'?policies():`<main><div class="title"><div><p class="eyebrow">SLAIV</p><h1>${active}</h1><p>This operational surface is available in the complete product roadmap.</p></div></div><section class="panel emptybig">No ${active.toLowerCase()} data is available in this demo.</section></main>`;document.querySelector('#app').innerHTML=sidebar()+`<div class="app">${topbar()}${content}</div><div id="drawer" class="drawer"></div>`; bind()}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{active=b.dataset.page;render()});document.querySelectorAll('[data-claim]').forEach(b=>b.onclick=()=>{selectedClaim=claims.find(c=>c.id===b.dataset.claim);document.querySelector('main').outerHTML=claimDetail(selectedClaim);bind()});document.querySelectorAll('[data-validator]').forEach(b=>b.onclick=()=>{selectedValidator=validators.find(v=>v.id===b.dataset.validator);active='Validator';render()});document.querySelectorAll('[data-prov]').forEach(b=>b.onclick=()=>openDrawer(b.dataset.prov));document.querySelector('#covered')?.addEventListener('click',()=>{coveredOnly=!coveredOnly;render()});document.querySelector('#validatorSearch')?.addEventListener('input',e=>{document.querySelectorAll('.trow').forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(e.target.value.toLowerCase()))});document.querySelector('#retry')?.addEventListener('click',e=>{e.target.textContent='Connection unavailable';e.target.disabled=true});document.querySelector('#createPolicy')?.addEventListener('click',()=>alert('Policy builder is ready for wallet and contract integration. Policy terms will be immutable after activation.'));document.querySelector('#newClaim')?.addEventListener('click',()=>alert('Claim submission requires a connected wallet, active policy, and evidence packet.'))}
function openDrawer(kind){let d=provenance[kind], drawer=document.querySelector('#drawer');drawer.className='drawer open';drawer.innerHTML=`<button class="close">×</button><small>PROVENANCE INSPECTION</small><h2>${kind}</h2>${['SOURCE TYPE','SOURCE','RETRIEVED AT','BLOCK / TX / URL','RAW EVIDENCE HASH','USED IN VERDICT?'].map((x,i)=>`<div><small>${x}</small><p>${d[i]}</p></div>`).join('')}<footer>Evidence is displayed for auditability; it is not a claim of live protocol data.</footer>`;drawer.querySelector('.close').onclick=()=>drawer.className='drawer'}
render();
